DROP DATABASE IF EXISTS TestIndexDB;
CREATE DATABASE TestIndexDB;
USE TestIndexDB;

CREATE TABLE IF NOT EXISTS Pais (
	id_nom CHAR(4),
    nom VARCHAR(70)


)ENGINE INNODB;


INSERT INTO Pais (id_nom, nom) VALUES ('P001','Afganistán');
INSERT INTO Pais (id_nom, nom) VALUES ('P002','Asia Central');
INSERT INTO Pais (id_nom, nom) VALUES ('P003','Albania');
INSERT INTO Pais (id_nom, nom) VALUES ('P004','Argelia');
INSERT INTO Pais (id_nom, nom) VALUES ('P005','Samoa Americana');
INSERT INTO Pais (id_nom, nom) VALUES ('P006','Andorra');
INSERT INTO Pais (id_nom, nom) VALUES ('P007','Angola');
INSERT INTO Pais (id_nom, nom) VALUES ('P008','Anguilla');
INSERT INTO Pais (id_nom, nom) VALUES ('P009','Antártida');
INSERT INTO Pais (id_nom, nom) VALUES ('P010','Antigua y Barbuda');
INSERT INTO Pais (id_nom, nom) VALUES ('P011','Argentina');
INSERT INTO Pais (id_nom, nom) VALUES ('P012','Armenia');
INSERT INTO Pais (id_nom, nom) VALUES ('P013','Aruba');
INSERT INTO Pais (id_nom, nom) VALUES ('P014','Australia');
INSERT INTO Pais (id_nom, nom) VALUES ('P015','Austria');
INSERT INTO Pais (id_nom, nom) VALUES ('P016','Azerbaiyán');
INSERT INTO Pais (id_nom, nom) VALUES ('P017','Bahamas');
INSERT INTO Pais (id_nom, nom) VALUES ('P018','Bahrein');
INSERT INTO Pais (id_nom, nom) VALUES ('P019','Bangladesh');
INSERT INTO Pais (id_nom, nom) VALUES ('P020','Barbados');
INSERT INTO Pais (id_nom, nom) VALUES ('P021','Bielorrusia');
INSERT INTO Pais (id_nom, nom) VALUES ('P022','Bélgica');
INSERT INTO Pais (id_nom, nom) VALUES ('P023','Belice');
INSERT INTO Pais (id_nom, nom) VALUES ('P024','Benín');
INSERT INTO Pais (id_nom, nom) VALUES ('P025','Bermudas');
INSERT INTO Pais (id_nom, nom) VALUES ('P026','Bután');
INSERT INTO Pais (id_nom, nom) VALUES ('P027','Bolivia');
INSERT INTO Pais (id_nom, nom) VALUES ('P028','Bosnia-Herzegovina');
INSERT INTO Pais (id_nom, nom) VALUES ('P029','Botswana');
INSERT INTO Pais (id_nom, nom) VALUES ('P030','Brasil');
INSERT INTO Pais (id_nom, nom) VALUES ('P031','Brunei Darussalam');
INSERT INTO Pais (id_nom, nom) VALUES ('P032','Bulgaria');
INSERT INTO Pais (id_nom, nom) VALUES ('P033','Burkina Faso');
INSERT INTO Pais (id_nom, nom) VALUES ('P034','Burundi');
INSERT INTO Pais (id_nom, nom) VALUES ('P035','Camboya');
INSERT INTO Pais (id_nom, nom) VALUES ('P036','Camerún');
INSERT INTO Pais (id_nom, nom) VALUES ('P037','Canadá');
INSERT INTO Pais (id_nom, nom) VALUES ('P038','Cabo Verde');
INSERT INTO Pais (id_nom, nom) VALUES ('P039','Islas Caimán');
INSERT INTO Pais (id_nom, nom) VALUES ('P040','República Centroafricana');
INSERT INTO Pais (id_nom, nom) VALUES ('P041','Chad');
INSERT INTO Pais (id_nom, nom) VALUES ('P042','Chile');
INSERT INTO Pais (id_nom, nom) VALUES ('P043','China');
INSERT INTO Pais (id_nom, nom) VALUES ('P044','Isla De Navidad. Isla Christmas');
INSERT INTO Pais (id_nom, nom) VALUES ('P045','Islas Cocos');
INSERT INTO Pais (id_nom, nom) VALUES ('P046','Colombia');
INSERT INTO Pais (id_nom, nom) VALUES ('P047','Comores');
INSERT INTO Pais (id_nom, nom) VALUES ('P048','República Democrática del Congo');
INSERT INTO Pais (id_nom, nom) VALUES ('P049','República del Congo');
INSERT INTO Pais (id_nom, nom) VALUES ('P050','Islas Cook');
INSERT INTO Pais (id_nom, nom) VALUES ('P051','Costa Rica');
INSERT INTO Pais (id_nom, nom) VALUES ('P052','Costa de Marfil');
INSERT INTO Pais (id_nom, nom) VALUES ('P053','Croacia');
INSERT INTO Pais (id_nom, nom) VALUES ('P054','Cuba');
INSERT INTO Pais (id_nom, nom) VALUES ('P055','Chipre');
INSERT INTO Pais (id_nom, nom) VALUES ('P056','República Checa');
INSERT INTO Pais (id_nom, nom) VALUES ('P057','Dinamarca');
INSERT INTO Pais (id_nom, nom) VALUES ('P058','Djibouti. Yibuti');
INSERT INTO Pais (id_nom, nom) VALUES ('P059','Dominica');
INSERT INTO Pais (id_nom, nom) VALUES ('P060','República Dominicana');
INSERT INTO Pais (id_nom, nom) VALUES ('P061','Timor Oriental');
INSERT INTO Pais (id_nom, nom) VALUES ('P062','Ecuador');
INSERT INTO Pais (id_nom, nom) VALUES ('P063','Egipto');
INSERT INTO Pais (id_nom, nom) VALUES ('P064','El Salvador');
INSERT INTO Pais (id_nom, nom) VALUES ('P065','Guinea Ecuatorial');
INSERT INTO Pais (id_nom, nom) VALUES ('P066','Eritrea');
INSERT INTO Pais (id_nom, nom) VALUES ('P067','Estonia');
INSERT INTO Pais (id_nom, nom) VALUES ('P068','Etiopía');
INSERT INTO Pais (id_nom, nom) VALUES ('P069','Islas Malvinas');
INSERT INTO Pais (id_nom, nom) VALUES ('P070','Islas Feroe');
INSERT INTO Pais (id_nom, nom) VALUES ('P071','Fiyi');
INSERT INTO Pais (id_nom, nom) VALUES ('P072','Finlandia');
INSERT INTO Pais (id_nom, nom) VALUES ('P073','Francia');
INSERT INTO Pais (id_nom, nom) VALUES ('P074','Guayana Francesa');
INSERT INTO Pais (id_nom, nom) VALUES ('P075','Polinesia Francesa');
INSERT INTO Pais (id_nom, nom) VALUES ('P076','Tierras Australes y Antárticas Francesas');
INSERT INTO Pais (id_nom, nom) VALUES ('P077','Gabón');
INSERT INTO Pais (id_nom, nom) VALUES ('P078','Gambia');
INSERT INTO Pais (id_nom, nom) VALUES ('P079','Georgia');
INSERT INTO Pais (id_nom, nom) VALUES ('P080','Alemania');
INSERT INTO Pais (id_nom, nom) VALUES ('P081','Ghana');
INSERT INTO Pais (id_nom, nom) VALUES ('P082','Gibraltar');
INSERT INTO Pais (id_nom, nom) VALUES ('P083','Gran Bretaña');
INSERT INTO Pais (id_nom, nom) VALUES ('P084','Grecia');
INSERT INTO Pais (id_nom, nom) VALUES ('P085','Groenlandia');
INSERT INTO Pais (id_nom, nom) VALUES ('P086','Granada');
INSERT INTO Pais (id_nom, nom) VALUES ('P087','Guadalupe');
INSERT INTO Pais (id_nom, nom) VALUES ('P088','Guam');
INSERT INTO Pais (id_nom, nom) VALUES ('P089','Guatemala');
INSERT INTO Pais (id_nom, nom) VALUES ('P090','República Guinea');
INSERT INTO Pais (id_nom, nom) VALUES ('P091','Guinea Bissau');
INSERT INTO Pais (id_nom, nom) VALUES ('P092','Guyana');
INSERT INTO Pais (id_nom, nom) VALUES ('P093','Spanish Name - Nombre Español');
INSERT INTO Pais (id_nom, nom) VALUES ('P094','Haiti');
INSERT INTO Pais (id_nom, nom) VALUES ('P095','Santa Sede. Vaticano. Ciudad del Vaticano');
INSERT INTO Pais (id_nom, nom) VALUES ('P096','Honduras');
INSERT INTO Pais (id_nom, nom) VALUES ('P097','Hong Kong');
INSERT INTO Pais (id_nom, nom) VALUES ('P098','Hungría');
INSERT INTO Pais (id_nom, nom) VALUES ('P099','Islandia');
INSERT INTO Pais (id_nom, nom) VALUES ('P100','India');
INSERT INTO Pais (id_nom, nom) VALUES ('P101','Indonesia');
INSERT INTO Pais (id_nom, nom) VALUES ('P102','Irán');
INSERT INTO Pais (id_nom, nom) VALUES ('P103','Iraq');
INSERT INTO Pais (id_nom, nom) VALUES ('P104','Irlanda');
INSERT INTO Pais (id_nom, nom) VALUES ('P105','Israel');
INSERT INTO Pais (id_nom, nom) VALUES ('P106','Italia');
INSERT INTO Pais (id_nom, nom) VALUES ('P107','Jamaica');
INSERT INTO Pais (id_nom, nom) VALUES ('P108','Japón');
INSERT INTO Pais (id_nom, nom) VALUES ('P109','Jordania');
INSERT INTO Pais (id_nom, nom) VALUES ('P112','Kazajstán');
INSERT INTO Pais (id_nom, nom) VALUES ('P113','Kenia');
INSERT INTO Pais (id_nom, nom) VALUES ('P114','Kiribati');
INSERT INTO Pais (id_nom, nom) VALUES ('P115','Corea del Norte');
INSERT INTO Pais (id_nom, nom) VALUES ('P116','Corea del Sur');
INSERT INTO Pais (id_nom, nom) VALUES ('P117','Kosovo');
INSERT INTO Pais (id_nom, nom) VALUES ('P118','Kuwait');
INSERT INTO Pais (id_nom, nom) VALUES ('P119','Kirguistán');
INSERT INTO Pais (id_nom, nom) VALUES ('P120','República Democrática Popular Lao');
INSERT INTO Pais (id_nom, nom) VALUES ('P121','Letonia');
INSERT INTO Pais (id_nom, nom) VALUES ('P122','Líbano');
INSERT INTO Pais (id_nom, nom) VALUES ('P123','Lesotho');
INSERT INTO Pais (id_nom, nom) VALUES ('P124','Liberia');
INSERT INTO Pais (id_nom, nom) VALUES ('P125','Libia');
INSERT INTO Pais (id_nom, nom) VALUES ('P126','Liechtenstein');
INSERT INTO Pais (id_nom, nom) VALUES ('P127','Lituania');
INSERT INTO Pais (id_nom, nom) VALUES ('P128','Luxemburgo');
INSERT INTO Pais (id_nom, nom) VALUES ('P129','Macao');
INSERT INTO Pais (id_nom, nom) VALUES ('P130','Macedonia');
INSERT INTO Pais (id_nom, nom) VALUES ('P131','Madagascar');
INSERT INTO Pais (id_nom, nom) VALUES ('P132','Malawi');
INSERT INTO Pais (id_nom, nom) VALUES ('P133','Malasia');
INSERT INTO Pais (id_nom, nom) VALUES ('P134','Maldivas');
INSERT INTO Pais (id_nom, nom) VALUES ('P135','Malí');
INSERT INTO Pais (id_nom, nom) VALUES ('P136','Malta');
INSERT INTO Pais (id_nom, nom) VALUES ('P137','Islas Marshall');
INSERT INTO Pais (id_nom, nom) VALUES ('P138','Martinica');
INSERT INTO Pais (id_nom, nom) VALUES ('P139','Mauritania');
INSERT INTO Pais (id_nom, nom) VALUES ('P140','Mauricio');
INSERT INTO Pais (id_nom, nom) VALUES ('P141','Mayotte');
INSERT INTO Pais (id_nom, nom) VALUES ('P142','México');
INSERT INTO Pais (id_nom, nom) VALUES ('P143','Micronesia');
INSERT INTO Pais (id_nom, nom) VALUES ('P144','Moldavia');
INSERT INTO Pais (id_nom, nom) VALUES ('P145','Mónaco');
INSERT INTO Pais (id_nom, nom) VALUES ('P146','Mongolia');
INSERT INTO Pais (id_nom, nom) VALUES ('P147','Montenegro');
INSERT INTO Pais (id_nom, nom) VALUES ('P148','Montserrat');
INSERT INTO Pais (id_nom, nom) VALUES ('P149','Marruecos');
INSERT INTO Pais (id_nom, nom) VALUES ('P150','Mozambique');
INSERT INTO Pais (id_nom, nom) VALUES ('P151','Myanmar. Birmania');
INSERT INTO Pais (id_nom, nom) VALUES ('P152','Namibia');
INSERT INTO Pais (id_nom, nom) VALUES ('P153','Nauru');
INSERT INTO Pais (id_nom, nom) VALUES ('P154','Nepal');
INSERT INTO Pais (id_nom, nom) VALUES ('P155','Países Bajos. Holanda');
INSERT INTO Pais (id_nom, nom) VALUES ('P156','Antillas Holandesas');
INSERT INTO Pais (id_nom, nom) VALUES ('P157','Nueva Caledonia');
INSERT INTO Pais (id_nom, nom) VALUES ('P158','Nueva Zelanda');
INSERT INTO Pais (id_nom, nom) VALUES ('P159','Nicaragua');
INSERT INTO Pais (id_nom, nom) VALUES ('P160','Niger');
INSERT INTO Pais (id_nom, nom) VALUES ('P161','Nigeria');
INSERT INTO Pais (id_nom, nom) VALUES ('P162','Niue');
INSERT INTO Pais (id_nom, nom) VALUES ('P163','Marianas del Norte');
INSERT INTO Pais (id_nom, nom) VALUES ('P164','Noruega');
INSERT INTO Pais (id_nom, nom) VALUES ('P165','Omán');
INSERT INTO Pais (id_nom, nom) VALUES ('P166','Pakistán');
INSERT INTO Pais (id_nom, nom) VALUES ('P167','Palau');
INSERT INTO Pais (id_nom, nom) VALUES ('P168','Territorios Palestinos');
INSERT INTO Pais (id_nom, nom) VALUES ('P169','Panamá');
INSERT INTO Pais (id_nom, nom) VALUES ('P170','Papúa-Nueva Guinea');
INSERT INTO Pais (id_nom, nom) VALUES ('P171','Paraguay');
INSERT INTO Pais (id_nom, nom) VALUES ('P172','Perú');
INSERT INTO Pais (id_nom, nom) VALUES ('P173','Filipinas');
INSERT INTO Pais (id_nom, nom) VALUES ('P174','Isla Pitcairn');
INSERT INTO Pais (id_nom, nom) VALUES ('P175','Polonia');
INSERT INTO Pais (id_nom, nom) VALUES ('P176','Portugal');
INSERT INTO Pais (id_nom, nom) VALUES ('P177','Puerto Rico');
INSERT INTO Pais (id_nom, nom) VALUES ('P178','Qatar');
INSERT INTO Pais (id_nom, nom) VALUES ('P179','Reunión');
INSERT INTO Pais (id_nom, nom) VALUES ('P180','Rumanía');
INSERT INTO Pais (id_nom, nom) VALUES ('P181','Federación Rusa');
INSERT INTO Pais (id_nom, nom) VALUES ('P182','Ruanda');
INSERT INTO Pais (id_nom, nom) VALUES ('P183','San Cristobal y Nevis');
INSERT INTO Pais (id_nom, nom) VALUES ('P184','Santa Lucía');
INSERT INTO Pais (id_nom, nom) VALUES ('P185','San Vincente y Granadinas');
INSERT INTO Pais (id_nom, nom) VALUES ('P186','Samoa');
INSERT INTO Pais (id_nom, nom) VALUES ('P187','San Marino');
INSERT INTO Pais (id_nom, nom) VALUES ('P188','Santo Tomé y Príncipe');
INSERT INTO Pais (id_nom, nom) VALUES ('P189','Arabia Saudita');
INSERT INTO Pais (id_nom, nom) VALUES ('P190','Senegal');
INSERT INTO Pais (id_nom, nom) VALUES ('P191','Serbia');
INSERT INTO Pais (id_nom, nom) VALUES ('P192','Seychelles');
INSERT INTO Pais (id_nom, nom) VALUES ('P193','Sierra Leona');
INSERT INTO Pais (id_nom, nom) VALUES ('P194','Singapur');
INSERT INTO Pais (id_nom, nom) VALUES ('P195','Eslovaquia');
INSERT INTO Pais (id_nom, nom) VALUES ('P196','Eslovenia');
INSERT INTO Pais (id_nom, nom) VALUES ('P197','Islas Salomón');
INSERT INTO Pais (id_nom, nom) VALUES ('P198','Somalia');
INSERT INTO Pais (id_nom, nom) VALUES ('P199','Sudáfrica');
INSERT INTO Pais (id_nom, nom) VALUES ('P200','Sudán del Sur');
INSERT INTO Pais (id_nom, nom) VALUES ('P201','España');
INSERT INTO Pais (id_nom, nom) VALUES ('P202','Sri Lanka');
INSERT INTO Pais (id_nom, nom) VALUES ('P203','Sudán');
INSERT INTO Pais (id_nom, nom) VALUES ('P204','Surinam');
INSERT INTO Pais (id_nom, nom) VALUES ('P205','Swazilandia');
INSERT INTO Pais (id_nom, nom) VALUES ('P206','Suecia');
INSERT INTO Pais (id_nom, nom) VALUES ('P207','Suiza');
INSERT INTO Pais (id_nom, nom) VALUES ('P208','Siria');
INSERT INTO Pais (id_nom, nom) VALUES ('P209','Taiwan');
INSERT INTO Pais (id_nom, nom) VALUES ('P210','Tadjikistan');
INSERT INTO Pais (id_nom, nom) VALUES ('P211','Tanzania');
INSERT INTO Pais (id_nom, nom) VALUES ('P212','Tailandia');
INSERT INTO Pais (id_nom, nom) VALUES ('P213','Tíbet');
INSERT INTO Pais (id_nom, nom) VALUES ('P214','Timor Oriental');
INSERT INTO Pais (id_nom, nom) VALUES ('P215','Togo');
INSERT INTO Pais (id_nom, nom) VALUES ('P216','Tokelau');
INSERT INTO Pais (id_nom, nom) VALUES ('P217','Tonga');
INSERT INTO Pais (id_nom, nom) VALUES ('P218','Trinidad y Tobago');
INSERT INTO Pais (id_nom, nom) VALUES ('P219','Túnez');
INSERT INTO Pais (id_nom, nom) VALUES ('P220','Turquía');
INSERT INTO Pais (id_nom, nom) VALUES ('P221','Turkmenistan');
INSERT INTO Pais (id_nom, nom) VALUES ('P222','Islas Turcas y Caicos');
INSERT INTO Pais (id_nom, nom) VALUES ('P223','Tuvalu');
INSERT INTO Pais (id_nom, nom) VALUES ('P224','Uganda');
INSERT INTO Pais (id_nom, nom) VALUES ('P225','Ucrania');
INSERT INTO Pais (id_nom, nom) VALUES ('P226','Emiratos Árabes Unidos');
INSERT INTO Pais (id_nom, nom) VALUES ('P227','Reino Unido');
INSERT INTO Pais (id_nom, nom) VALUES ('P228','Estados Unidos');
INSERT INTO Pais (id_nom, nom) VALUES ('P229','Uruguay');
INSERT INTO Pais (id_nom, nom) VALUES ('P230','Uzbekistán');
INSERT INTO Pais (id_nom, nom) VALUES ('P231','Vanuatu');
INSERT INTO Pais (id_nom, nom) VALUES ('P232','Ciudad del Vaticano');
INSERT INTO Pais (id_nom, nom) VALUES ('P233','Venezuela');
INSERT INTO Pais (id_nom, nom) VALUES ('P234','Vietnam');
INSERT INTO Pais (id_nom, nom) VALUES ('P235','Islas Virgenes Británicas');
INSERT INTO Pais (id_nom, nom) VALUES ('P236','Islas Virgenes Americanas');
INSERT INTO Pais (id_nom, nom) VALUES ('P237','Wallis y Futuna');
INSERT INTO Pais (id_nom, nom) VALUES ('P238','Sáhara Occidental');
INSERT INTO Pais (id_nom, nom) VALUES ('P239','Yemen');
INSERT INTO Pais (id_nom, nom) VALUES ('P240','Zambia');
INSERT INTO Pais (id_nom, nom) VALUES ('P241','Zimbabwe');

select * from pais;

select * from pais where nom='Yemen';

insert into pais select * from pais where id_nom between 'P200' and 'P241';

